### ISSUE TITLE
칸막이 위치 고정하기

### ISSUE THREAD

**Issue by vhv3y8** [vhv3y8/monotony-Web#1]
현재 상황
```css
squareContainer: {
  flex: 1,
  flexDirection: "row",
  alignItems: "flex-start",
  justifyContent: "flex-start",
},
```
```css
squareDiv: {
  flex: 1,
  flexDirection: "column",
  flexWrap: "nowrap",
  width: 300,
  height: 300,
  margin: 20,
},
```
문제점
* squareDiv가 가로로 한 칸을 차지함  
* 그래서 squareContainer는 row인데도 불구하고 세로로 정렬된 상태
* * *
* 아까 다르게 했었을때는 칸막이마다 높이가 달랐다. 어쨌든 고정을 해야함
