### ISSUE TITLE
header 안의 태그들 margin 0으로 만들기

### ISSUE THREAD

**Issue by vhv3y8** [vhv3y8/monotony-Web#2]
```css
main: {
  ...

  ">*" : {
    margin: 0
  }
```
이런 식으로 하고 싶은데 이게 안통함.
`overflow: "hidden"`이나 다른 방법으로 하면 안에것들 다 퍼센트 씌워야 할 것 같아서 싫음
